"""Delete views and add discord url for post

Revision ID: d83f496be234
Revises: 6825a6064a7b
Create Date: 2025-01-05 17:29:23.764493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83f496be234'
down_revision: Union[str, None] = '6825a6064a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('discord_url', sa.String(), nullable=True))
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'discord_url')
    # ### end Alembic commands ###
