"""Return image url in posts, donations, users

Revision ID: 11777d8f6c8a
Revises: c4e9d7376ee6
Create Date: 2025-01-11 20:21:43.185054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11777d8f6c8a'
down_revision: Union[str, None] = 'c4e9d7376ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skin_url')
    op.drop_column('posts', 'image_url')
    op.drop_column('donations', 'image_url')
    # ### end Alembic commands ###
