"""Change donation, delete relationship with user

Revision ID: 25896831eced
Revises: 34b6389eb12f
Create Date: 2025-01-05 18:59:32.551325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25896831eced'
down_revision: Union[str, None] = '34b6389eb12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('name', sa.String(), nullable=False))
    op.add_column('donations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('donations', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('donations', sa.Column('category', sa.String(), nullable=False))
    op.add_column('donations', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_constraint('donations_user_id_fkey', 'donations', type_='foreignkey')
    op.drop_column('donations', 'package_name')
    op.drop_column('donations', 'amount')
    op.drop_column('donations', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('donations', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('donations', sa.Column('package_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('donations_user_id_fkey', 'donations', 'users', ['user_id'], ['id'])
    op.drop_column('donations', 'image_url')
    op.drop_column('donations', 'category')
    op.drop_column('donations', 'price')
    op.drop_column('donations', 'description')
    op.drop_column('donations', 'name')
    # ### end Alembic commands ###
