"""Add purchasedDonation

Revision ID: 3cd7c21dc870
Revises: 98a043d9f7d6
Create Date: 2025-01-28 17:19:00.995027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd7c21dc870'
down_revision: Union[str, None] = '98a043d9f7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchased_donations_id'), 'purchased_donations', ['id'], unique=False)
    op.alter_column('payment_history', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payment_history', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('payment_history_transaction_id_key', 'payment_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('payment_history_transaction_id_key', 'payment_history', ['transaction_id'])
    op.alter_column('payment_history', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payment_history', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_purchased_donations_id'), table_name='purchased_donations')
    op.drop_table('purchased_donations')
    # ### end Alembic commands ###
