"""Add skin url in user model

Revision ID: c2dc9edca853
Revises: dd188b50ddec
Create Date: 2025-01-07 12:27:40.187148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2dc9edca853'
down_revision: Union[str, None] = 'dd188b50ddec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skin_url')
    # ### end Alembic commands ###
