"""Delete image_url from post and donation

Revision ID: c4e9d7376ee6
Revises: d73b580c64b3
Create Date: 2025-01-11 19:41:50.780495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e9d7376ee6'
down_revision: Union[str, None] = 'd73b580c64b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'image_url')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('donations', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
