"""Delete rows skin_url from user table

Revision ID: d73b580c64b3
Revises: c02a281f2709
Create Date: 2025-01-11 19:13:44.146590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73b580c64b3'
down_revision: Union[str, None] = 'c02a281f2709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skin_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skin_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
