"""Delete skin from database

Revision ID: dd188b50ddec
Revises: 4fe65e222804
Create Date: 2025-01-07 12:26:16.267355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd188b50ddec'
down_revision: Union[str, None] = '4fe65e222804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skins_id', table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='skins_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='skins_pkey')
    )
    op.create_index('ix_skins_id', 'skins', ['id'], unique=False)
    # ### end Alembic commands ###
